# Individual Plan

### github: https://github.com/kaiii246/project.git

## 1. Load package

In [3]:
library(tidyverse)
library(tidymodels)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
── Attaching packages ────────────────────────────────────── tidymodels 1.1.1 ──

✔ broom        1.0.6     ✔ rsample      1.2.1
✔ dials        1.3.0     ✔ tune         1.1.2
✔ infer        1.0.7     ✔ workflows    1.1.4
✔ modeldata    1.4.0     ✔ workflowsets 1.0.1
✔ parsnip      1.2.1     ✔ yardstick    1.3.1
✔ recipes      1.1.0

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use suppressPackageStartupMessages() to eliminate package startup messages

## 2. Import data

In [4]:
url = "https://drive.google.com/uc?export=download&id=1gl3xMGBBIjHpG4kwIY-g84_ijx2sQYIa"
players <- read_csv(url)
dim(players); head(players)

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 196   7

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

In [5]:
url = "https://drive.google.com/uc?export=download&id=1xUdR3ObrkAnCQM8HAPRtSIW1SASHwarJ"
sessions <- read_csv(url)
dim(sessions); head(sessions)

Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 1535    5

  hashedEmail
1 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
4 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
5 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
6 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
  start_time       end_time         original_start_time original_end_time
1 30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2 17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3 25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
4 25/07/2024 03:22 25/07/2024 03:58 1.72188e+12         1.72188e+12
5 25/05/2024 16:01 25/05/2024 16:12 1.71665e+12         1.71665e+12
6 23/06/2024 15:08 23/06/2024 17:10 1.71916e+12         1.71916e+12

## 3. Data Description

 + ### players.csv

In [6]:
summary(players)

  experience        subscribe       hashedEmail         played_hours
 Length:196         Mode :logical   Length:196         Min.   :  0.000
 Class :character   FALSE:52        Class :character   1st Qu.:  0.000
 Mode  :character   TRUE :144       Mode  :character   Median :  0.100
                                                       Mean   :  5.846
                                                       3rd Qu.:  0.600
                                                       Max.   :223.100

     name              gender               Age
 Length:196         Length:196         Min.   : 9.00
 Class :character   Class :character   1st Qu.:17.00
 Mode  :character   Mode  :character   Median :19.00
                                       Mean   :21.14
                                       3rd Qu.:22.75
                                       Max.   :58.00
                                       NA's   :2

+ **Observation**:196
+ **Summary Statistics**:
  

   played_hours:
   Min.   :  0.000 
   Median :  0.100 
   Mean   :  5.846 
   Max.   :223.100

   Age:
   Min.   : 9.00 
   Median :19.00 
   Mean   :21.14 
   Max.   :58.00

   subscribe:
   FALSE:52 
   TRUE :144 
+ **Variables**:7  
  1.experience: Categorical. The experience of the player has in Minecraft.  
  2.subscribe: Categorical. If the player subscribled to a game-related news.  
  3.hashedEmail: Categorical. The email of players.  
  4.played_hours: Numerical. The number of hours a player played on the PlaiCraft server.  
  5.name: Categorical. The players' names.  
  6.gender: Categorical. The players' gender.  
  7.Age: Numerical. The age of player.

+ ### sessions.csv

In [7]:
summary(sessions)

 hashedEmail         start_time          end_time         original_start_time
 Length:1535        Length:1535        Length:1535        Min.   :1.712e+12
 Class :character   Class :character   Class :character   1st Qu.:1.716e+12
 Mode  :character   Mode  :character   Mode  :character   Median :1.719e+12
                                                          Mean   :1.719e+12
                                                          3rd Qu.:1.722e+12
                                                          Max.   :1.727e+12

 original_end_time
 Min.   :1.712e+12
 1st Qu.:1.716e+12
 Median :1.719e+12
 Mean   :1.719e+12
 3rd Qu.:1.722e+12
 Max.   :1.727e+12
 NA's   :2

+ **Observation**:196
+ **Summary Statistics**:

  original_start_time:
  Min.   :1.712e+12
  Median :1.719e+12
  Mean   :1.719e+12
  Max.   :1.727e+12

  original_end_time:
  Min.   :1.712e+12
  Median :1.719e+12
  Mean   :1.719e+12
  Max.   :1.727e+12
+ **variables**:5  
  1.hashedEmail: Categorical. The email of players.  
  2.start_time: Categorical. The start time of a player's session.  
  3.end_time: Categorical. The end time of a player's session.  
  4.original_start_time: Numerical. The numerical representation of start_time.  
  5.original_end_time: Numerical. The numerical representation of end_time.

### Issues  
1. The minimum player_hours is 0, which means someone registered for the game but did nothing.It may cause bias.
2. The median player_hours is 0.1, which is pretty small. It means that the data of many participants may not be very valuable beacuse they hardly played at all.
3. There are 2 NA's in Age and original_end_time.

## 4. Question

**Broad Question**: What player characteristics and behaviours are most predictive of subscribing to a game-related newsletter, and how do these features differ between various player types?  
**Specific Question**: To what extent can player demographics and in-game behaviour predict whether a Minecraft research participant subscribes to the newsletter?

### Data Wranging

+ Remove the players with no participation.

In [9]:
players_clean <- filter(players, played_hours > 0)
head(players_clean)

  experience subscribe
1 Pro        TRUE
2 Veteran    TRUE
3 Amateur    TRUE
4 Regular    TRUE
5 Amateur    TRUE
6 Veteran    TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
4 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
5 8b71f4d66a38389b7528bb38ba6eb71157733df7d1740371852a797ae97d82d1  0.1
6 7a4686586d290c67179275c7c3dfb4ea02f4d317d9ee0e2cee98baa27877a875  1.6
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Flora     Female 21
4 Kylie     Male   21
5 Natalie   Male   47
6 Lane      Female 23

## 5. Visualization